### ISSUE TITLE
Date and Time Pickers need default dates and times

### ISSUE THREAD

**Issue by noahread** [moxiworks/mds#183]
To avoid having to make a decision about a default date and time in every place in the product these components are used we want to have a universal default. 

- This default should be able to be overridden if wanted. It can be overridden to a different date or time, or can be overridden to be empty.
- The default for the date picker should be today’s date
- The default for the time picker should be the next hour from now. For example, if it is currently 3:17 pm the default should be for 4:00pm. If this is not possible, the default for the time picker should be 12:00pm.

**Comment by iamjpg** [comment]
@noahread This feels like an anti-pattern from a UX  date picker default standpoint. I don't know of one date time picker that works this way. Just to quote this article on date time picker best practices https://uxplanet.org/date-picker-design-best-practices-41bd522f10a5

> Should the input field contain default prepopulated values?
The answer to this question in the context of your form and the information you know about your users. In a nutshell, it’s a good idea to prepopulate the dates only if you are certain that the user is likely to choose these dates.
Avoid setting random values. Setting random values for the user will force users to change the values to the ones they are actually looking for. It will introduce extra work and increase the interaction cost.

It's my feeling that even with this change we'd need to still make a decision about what the default will be every time the picker is used. I agree, as a user, to the quote above. If the date field is populated and I don't want it to be, it would annoy me to have to remove the value. Also, shouldn't the default be a case by case decision by product?

I'm really just trying to understand the decision around this more.

**Comment by noahread** [comment]
That's a good point. What do you think about having a default time in the time picker?

**Comment by iamjpg** [comment]
To me, it feels like the same issue. I think that whatever we do, like you mentioned above, we should be consistent. If we do default the time picker we should do the same with the date picker.

What if we made it a simple property to pass to make `now` be the default when the component loads? Essentially lessening the barrier for populating the current date and time?

I have one other idea - if the field is `required` maybe then we default to current date time?

**Comment by noahread** [comment]
I like the idea of having an optional **now** prop you can pass if you want a default, but otherwise the default is empty.

However, how much is this actually adding, since I’m assuming the dev can pass a value as the default anyway? You've started to convince me that leaving things as they are may be best.

**Comment by iamjpg** [comment]
Closing this issue in favor of the documentation ticket which has come from the conversation.
