### ISSUE TITLE
Create a Percentage Based Loader

### ISSUE THREAD

**Issue by iamjpg** [moxiworks/mds#204]
In the MDS update there will be a percentage based loader. We also have a request for one inside our CSV upload feature in Nucleus.

* Increment by a `%` every `n` seconds and when the request ends the loader can zip to `100%`

The percentage and the `n` seconds can be set with sensible defaults (5% every second?)

This ticket is for tracking purposes.

**Comment by kevinleedrum** [comment]
Added to v0.1.49.
