### ISSUE TITLE
Implement New Mercury Component: Dialogs

### ISSUE THREAD

**Issue by michsu13** [moxiworks/mds#217]
**Add the following dialog components:**
• Simple Dialogs
• Variable Dialogs

**See designs here:**
https://www.figma.com/file/c87gg73jZlg3tvrPIdW8TA/Mercury---Components?node-id=2860%3A24514

**See prototype here:**
https://playful-marshmallow-9e8d7f.netlify.app/dialogs

**Mapping to Shirley:**
Simple Dialog (same)
Variable Dialog = Advanced Dialog

**Comment by johnmcclumpha** [comment]
Dialogs have been updated in this PR: https://github.com/moxiworks/mds/pull/266
